name: '04 - Doxygen'

on:
  push:
    branches:
      - master
    paths:
      - 'homework/doxygen/**'
      - '.github/**'
      - 'CMakeLists.txt'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake .
        working-directory: homework/doxygen
      - run: make
        working-directory: homework/doxygen
      - run: mkdir -p homework/doxygen/docs/04-doxygen
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'homework/doxygen'
          doxyfile-path: 'Doxygen'
      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: homework/doxygen/docs